---
- name: Credentials | SSH Key bind mount directory
  file:
    path: "/var/lib/lxc/files/ssh"
    state: directory
    mode: 0700

- name: Credentials | authorized_keys
  template:
    src: ssh-keys.j2
    dest: "/var/lib/lxc/files/ssh/authorized_keys"
    mode: 0600
